apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-bvwa
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0054-tenant/tkrw-pr712-0075-0054-app/devfile-sample-bvwa@sha256:cca8485f352396cc9af9a830de30341b1793f6a82129c60a9e71339b4e98caa6
        name: my-nodejs
        resources: {}
status: {}
